FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# BloodAlert

The Blood Alert Web API offers different functionalities for managing blood donation, 
and to advertise and promote blood donation in blood banks. Blood Alert Web API will facilitate effective communication between a blood donor, and a blood bank,
managing blood level information of all blood types in blood banks, tracking blood donation history of 
donated individuals. 
# Group Link Relations

# Group Profiles

## Blood Bank Profile [/profiles/blood-banks-profile]

Profile definition for all Blood bank  related resources.

## Blood Donor Profile [/profiles/blood-donors-profile]

Profile definition for all Blood Donor related resources.
## Blood Types Profile [/profiles/blood-types-profile]

Profile definition for all Blood Type related resources.

### Dependencies


# Group Blood Banks

All these resources use the [Blood Bank Profile](reference/profiles/blood-bank-profile).

## Blood Bank List [/BloodAlert/bloodbank]
All Blood Banks in the database

### List All Blood Banks [GET]

Get a list of all Blood Banks in the system

+ Response 200 (application/vnd.mason+json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a Blood Bank [POST]

Adds a new Blood Bank to the bloodAlert database
+ Request (application/json)
    
    The following are optional and defaults to `None`
    + `latitude`
    + `latitude`

    + Headers
    
            Accept: application/vnd.mason+json
    + Body
    
            {
                "name": "Oulun Tervestalo Veri Palvelu",
                "address": "Kajaanintie 50",
                "city": "Oulu",
                "telephone": "+358 8 3152011", 
                "email": "OuluUniHospital@oulu.fi",
                "latitude": 65.007406, "longitude": 25.517786,
                "threshold": 30
            }

+ Response 201 (application/json)
Blood Bank Created sucessfully
    + Headers

            Location: Url to the created Blood bank


+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format"
                    "@messages": [
                        "Be sure to include "
                    ]
                }
                "resource_url": "/bloodAlert/BloodBanks/"
            }


+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type"
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                }
                "resource_url": "/bloodAlert/BloodBanks/"
            }

+ Response 500  (application/vnd.mason+json)

    The server cannot store the message in the database.
    
    + Body 

            {
                "@error": {
                    "@message": "Blood bank could not be created"
                    "@messages": [
                        "Cannot create a blood the blood bank in the database"
                    ]
                }
                "resource_url": "/bloodAlert/BloodBanks/"
            }

## Blood Bank [/bloodalert/bloodbanks/{bloodBankId}]
A blood bank information in the database

+ Parameters
    + bloodBankId (string) - the Id of the blood bank in the format bbank-\d{1,3}
                

### Get Blood Bank [GET]

Gets a blood bank information in the database


+ Request(application/json)
    
    +   Headers
    
            Accept: application/vnd.mason+json
            
+ Response  201 (application/vnd.mason+json)

    Blood bank information loaded sucessfully
    
    + Body
    
            {
                
        
            }
 
        
            
+ Response 404 (application/vnd.mason+json)
No such blood bank with specified Id

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood Bank"
                    "@messages": [
                        "No such blood bank with specified bbank-1"
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1"
            }
   
### Modify Blood Bank [PUT]

Modifies a blood bank 

+ Request(application/json)

  
    Any or a combination of any of the optional parameters can be used
    
    + Headers
    
            Accept: application/vnd.mason+json
            
    + Body
    
            {
                
                "name": "Oulun Tervestalo Veri Palvelu",
                "address": "Kajaanintie 50",
                "city": "Oulu",
                "telephone": "+358 8 3152011", 
                "email": "OuluUniHospital@oulu.fi",
                "latitude": 65.007406, "longitude": 25.517786,
                "threshold": 30,
                "latitude":1.4539303039,
                "longitude":5.038377333
            
            }
            
+ Response 204 (application/vnd.mason+json)
    
  

+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format"
                    "@messages": [
                        "Be sure to include all required parameters in the correct format "
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1"
            }
            
+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type"
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                }
                "resource_url": "/bloodalert/donors/"
            }

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank"
                    "@messages": [
                        " No such blood bank with id `bbank-1` exists in the database"
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1"
            }    
### Delete Blood Bank [DELETE]
Delete a message from the system

+ Request(application/json)
    
    + Headers
    
            Accept: application/vnd.mason+json
    
+ Response 204

        
        

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank"
                    "@messages": [
                        " No such blood bank with id `bbank-1` exists in the database"
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1"
            } 

## Blood Bank Blood levels [/bloodalert/bloddbanks/{bloodBankId}/bloodlevels/]
All blood levels (blood type and level of blood) of a particular blood bank

+ Parameters
    + bloodBankId (string) - the Id of the blood bank in the format bbank-\d{1,3}

### Get Blood Bank blood levels [GET]

+ Request(application/json)

    +   Headers
        
                Accept: application/vnd.mason+json
                
+ Response 201 (application/vnd.mason+json)
Blood bank blood levels loaded sucessfully 
    +   Body
            
            {
            
            }
            
+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank"
                    "@messages": [
                        " No such blood bank with id `bbank-1` exists in the database"
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1"
            }
## Blood Bank History List [/bloodalert/bloddbanks/{bloodBankId}/history/]
All blood bank blood transaction (donation , others) history
+ Parameters
    + bloodBankId (string) - the Id of the blood bank in the format bbank-\d{1,3}
    

### Get Blood Bank History List [GET]
Get all blood transactions of target blood bank (donation, etc)
+ Request(application/json)
    
    +   Headers
    
            Accept: application/vnd.mason+json
            
+ Response  201 (application/vnd.mason+json)

    Blood bank history List loaded sucessfully
    
    + Body
    
            {
                
        
            }
 
        
            
+ Response 404 (application/vnd.mason+json)
No such blood bank with specified Id

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood Bank"
                    "@messages": [
                        "No such blood bank with specified bbank-1"
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1/history"
            }
## Blood Bank History [/bloodalert/bloddbanks/{bloodBankId}/history/{historyId}/]
All blood bank blood transaction (donation , others) history
+ Parameters
    + bloodBankId (string) - the Id of the blood bank in the format bbank-\d{1,3}, example `bbank-1`
    + historyId (string)   - the Id of the blood Bank history entry in the format history -\d{1,3}, example `history-1`

### Get Blood Bank History [GET]
Get a single blood bank history entry of target historyId

+ Request(application/json)
    
    +   Headers
    
            Accept: application/vnd.mason+json
            
+ Response  201 (application/vnd.mason+json)

    Blood bank history information loaded sucessfully
    
    + Body
    
            {
                
        
            }
 
        
            
+ Response 404 (application/vnd.mason+json)
No such blood bank  with specified Blood bloodBankId or historyId

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood Bank"
                    "@messages": [
                        "No such blood bank with specified bbank-1"
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            }

### Modify Blood Bank History [PUT]
Modifies blood bank history 

+ Request(application/json)
    
    Any of ( or a combination of ) the following of a Blood Bank History ;
    
    + ``donorId``
    + ``bloodTypeId``
    + ``amount``
    + ``timeStamp``
    +   Headers
    
            Accept: application/vnd.mason+json
            
+ Response 204 (application/vnd.mason+json)
    
  

+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format"
                    "@messages": [
                        "Be sure to include all required parameters in the correct format "
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            }
            
+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type"
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                }
                "resource_url": "/bloodalert/donors/"
            }

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` and historyId `history-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank history"
                    "@messages": [
                        "No such blood bank with id `bbank-1` and historyId `history-1` exists in the database"
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            }         

### Delete Blood Bank History [DELETE]
Delete a blood bank donation history from the database

+ Request(application/json)
    
    + Headers
    
            Accept: application/vnd.mason+json
    
+ Response 204

        
        

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` and historyId `history-1` exists in the databaseNo such blood bank with id `bbank-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank history"
                    "@messages": [
                        "No such blood bank with id `bbank-1` and historyId `history-1` exists in the database"
                    ]
                }
                "resource_url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            } 


# Group Blood Donors

All these resources use the [Blood Donor Profile](reference/profiles/blood-donor-profile).

## Blood Donor List [/bloodalert/donors/]
All Blood Donors in the database

### List all Blood Donors  [GET]
Gets a list of all blood donors 
            
+ Response  201 (application/vnd.mason+json)

    Blood donor List loaded sucessfully
    
    + Body
    
            {
                
        
            }

### CREATE a new Blood Donor [POST]

Adds a new Blood Donor to the bloodAlert database
+ Request (application/json)
    
    The following are optional  
    + `address` defaults to `-`
    + `city` defaults to `None`
   

    + Headers
    
            Accept: application/vnd.mason+json
    + Body
    
            {
                "firstname": "Anna",
                "familyName": "Bord",
                "telephone": "+348416754234", 
                "email": "AnB@oulu.fi",
                "bloodTypeId": "btype-1", 
                "birthDate": "30-12-1986",
                "gender": "Female",
                "address": "Yliopistokatu 46 , Linnanmaa",
                "city": "Oulu"
            }

+ Response 201 (application/json)
Blood donor Created sucessfully
    + Headers

            Location: Url to the created Blood bank


+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format"
                    "@messages": [
                        "Be sure to include "
                    ]
                }
                "resource_url": "/bloodalert/donors/"
            }


+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type"
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                }
                "resource_url": "/bloodalert/donors/"
            }

+ Response 500  (application/vnd.mason+json)

    The server cannot store the message in the database.
    
    + Body 

            {
                "@error": {
                    "@message": "Blood donor could not be created"
                    "@messages": [
                        "Cannot create a blood the blood donor in the database"
                    ]
                }
                "resource_url": "/bloodalert/donors/"
            }

## Blood Donor [/bloodalert/donors/{donorid}/]
A blood donor in the database

+ Parameters
    + donorid (string) - the Id of the blood donor in the format bdonor-\d{1,3}
    
# Group Blood Types

All these resources use the [Blood Type Profile](reference/profiles/blood-types-profile).





    
