FORMAT: 1A
HOST: http://localhost:5000/

# BloodAlert

The Blood Alert Web API offers different functionalities for managing blood donation, 
and to advertise and promote blood donation in blood banks. Blood Alert Web API will facilitate effective communication between a blood donor, and a blood bank,
managing blood level information of all blood types in blood banks, tracking blood donation history of 
donated individuals. 



# Group Link Relations 

This document uses IANA standard link relations (http://www.iana.org/assignments/link-relations/link-relations.xhtml). In addition the following link relations have been defined:

## blood-banks-all [/link-relations/blood-banks-all]

This action list all registered in the system blood banks. Each item is an instance of the type Blood Bank defined in the profile Blood Bank Profile. Use via GET.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## add-blood-bank [/link-relations/add-blood-bank]

Creates a new Blood Bank. Use via POST.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)


## blood-types-all [/link-relations/blood-types-all]

This action list of all blood types. Use via GET.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## add-blood-type [/link-relations/add-blood-type]

Creates new blood type. Use via POST.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## edit [/link-relations/edit]

Edit the current context. Use via PUT.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## delete [/link-relations/delete]

Deletes the current context. Use via DELETE.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## blood-bank-history-list [/link-relations/blood-bank-history-list]

This action list all blood donations and transactions of the current blood bank. Each item is an instance of the type History defined in this profile. Can only be accessed through GET.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## blood-bank-blood-level [/link-relations/blood-bank-blood-level]

This action shows blood levels of the current blood bank. Use via GET.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## donors-all [/link-relations/donors-all]

This action list all registered in the system blood donors. Each item is an instance of the type Blood Donord defined in the profile Donor Profile. Use via GET.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)
## blood-donor-history-list [/link-relations/blood-donor-history-list]

This action list all blood donations of the current blood donor. Each item is an instance of the type History defined in this profile. Can only be accessed through GET.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## add-blood-donor [/link-relations/add-blood-donor]

Creates a new Blood Donor. Use via POST.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)

## blood-donor-donate [/link-relations/blood-donor-donate]

Creates a new Blood Donor donation. Use via POST.

### GET

Return the link relation description in HTML format
+ Response 200 (text/html)



# Group Profiles

## Blood Bank Profile [/profiles/blood-banks-profile]

Profile definition for all Blood bank  related resources.

### Dependencies

This profile inherits:
 * Some semantic descriptors from http://schema.org/Article
 * Some link  relations from IANA Web linking [RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml)

### Link relations

 * [donors-all](reference/link-relations/donors-all)
 * [blood-types-all](reference/link-relations/blood-types-all)
 * [edit](reference/link-relations/edit)
 * [delete](reference/link-relations/delete)
 * [blood-bank-history-list](reference/link-relations/blood-bank-history-list)
 * [blood-bank-blood-level](reference/link-relations/blood-bank-blood-level)
 
 Inherited from [IANA RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml)
 * `profile`: See [profile](https://tools.ietf.org/html/rfc6906). The link contains the location of the resource profile. 

### Semantic Descriptors

#### Data Type Message

 * `bloodBankId` (string): ID of the Blood Bank. 
 * `name`(string): Name of a Blood Bank. 
 * `city`(string): Name of the city where the Blood Bank is located.
 * `threshold`(object): Threshold for the Blood Level in the Bank. Is used to send the Alarm Messages to Blood Donors.
 
 Inherited from [http://schema.org/](http://schema.org/)
 * `address`(string): See [http://schema.org/address](https://schema.org/address)
 * `telephone`(string): See [http://schema.org/telephone](http://schema.org/telephone)
 * `email`(string): See [http://schema.org/email](http://schema.org/email)
 * `latitude`(string): See [https://schema.org/latitude](https://schema.org/latitude)
 * `longitude`(string): See [https://schema.org/longitude](https://schema.org/longitude)

### GET

Return Blood Bank Profile in HTML format
+ Response 200 (text/html)

## Blood Donor Profile [/profiles/blood-donors-profile]

Profile definition for all Blood Donor related resources.

### Dependencies

This profile inherits:
 * Some semantic descriptors from http://schema.org/Article
 * Some link  relations from IANA Web linking [RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml)

### Link relations

 * [blood-banks-all](reference/link-relations/blood-banks-all)
 * [blood-types-all](reference/link-relations/blood-types-all)
 * [edit](reference/link-relations/edit)
 * [delete](reference/link-relations/delete)
 * [blood-donor-history-list](reference/link-relations/blood-donor-history-list)
 * [blood-donor-donate](reference/link-relations/blood-donor-donate)
 
 Inherited from [IANA RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml)
 * `profile`: See [profile](https://tools.ietf.org/html/rfc6906). The link contains the location of the resource profile. 

### Semantic Descriptors

#### Data Type Message

 * `donorId` (string): ID of the Blood Donor in the system.
 * `bloodTypeId` (string): ID of the Blood Type of the current Blood Donor.
 * `city`(string): Name of the city where the Blood Donor is lives.
 
 Inherited from [http://schema.org/](http://schema.org/)
 * `firstname`(string): See [http://schema.org/givenName](http://schema.org/givenName)
 * `familyName`(string): See [http://schema.org/familyName](http://schema.org/familyName)
 * `birthday`(string): See [http://schema.org/birthDate](http://schema.org/birthDate)
 * `gender`(string): See [http://schema.org/gender](http://schema.org/gender)
 * `telephone`(string): See [http://schema.org/telephone](http://schema.org/telephone)
 * `address`(string): See [http://schema.org/address](https://schema.org/address)
 * `email`(string): See [http://schema.org/email](http://schema.org/email)

### GET

Return Blood Donor Profile in HTML format
+ Response 200 (text/html)


## Blood Types Profile [/profiles/blood-types-profile]

Profile definition for all Blood Type related resources.

### Dependencies

This profile inherits:
 * Some link  relations from IANA Web linking [RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml)

### Link relations

 * [blood-banks-all](reference/link-relations/blood-banks-all)
 * [donors-all](reference/link-relations/donors-all)
 * [edit](reference/link-relations/edit)
 * [delete](reference/link-relations/edit)
 
 Inherited from [IANA RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml)
 * `profile`: See [profile](https://tools.ietf.org/html/rfc6906). The link contains the location of the resource profile. 

### Semantic Descriptors

#### Data Type Message

 * `bloodTypeId` (string): ID of the Blood Type.
 * `name`(string): Name of a Blood Type. 

### GET

Return Blood Type Profile in HTML format
+ Response 200 (text/html)

## Error Profile [/profiles/error-profile]

Profile definition for all errors messages in the system

+ Attributes 
    + resource_url (string, required) - A url of the resource generating the error

### GET

Return the Error Profile in HTML format
+ Response 200 (text/html)



# Group Blood Banks

All these resources use the [Blood Bank Profile](reference/profiles/blood-bank-profile).

In addition all error messages follow the profile defined [Error Profile](reference/profiles/error-profile).

## Blood Bank List [/bloodalert/bloodbanks]
All Blood Banks in the database

### List All Blood Banks [GET]

Get a list of all Blood Banks in the system

+ Response 200 (application/vnd.mason+json)
    
    Blood Bank List loaded sucessfully
    
     
    + Body 
    
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalart/link-relations/"
                    }
                },
                "items": [
                    {
                        "bloodBankId": "bbank-1",
                        "name": "Oulu University Hospital", 
                        "address": "Kajaanintie 50",
                        "city":"Oulu",
                        "telephone":"+358 8 3152011",
                        "email": "OuluUniHospital@oulu.fi",
                        "latitude": 65.007406, 
                        "longitude": 25.517786,
                        "threshold": 30,
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/bloodbanks/bbank-1/"
                            },
                            "profile": {
                                "href": "/profiles/blood-banks-profile/"
                            }                            
                        }
                    },
                    {
                        "bloodBankId": "bbank-2",
                        "name": "Tervestalo", 
                        "address": "Yliopistokatu 1A",
                        "city":"Oulu",
                        "telephone":"+348 4 17860673",
                        "email": "Terveystalo@oulu.fi",
                        "latitude": 65.057774, 
                        "longitude": 25.4712876,
                        "threshold": 20,
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/bloodbanks/bbank-2/"
                            },
                            "profile": {
                                "href": "/profiles/blood-banks-profile/"
                            }                            
                        }
                    }
                ],
                "@controls": {
                    "self": {
                        "href": "/bloodalert/bloodbanks/"
                    },
                    "bloodalert:add-blood-bank": {
                        "title": "Add Blood Bank",
                        "href": "/bloodalert/bloodbanks/",
                        "encoding": "json",
                        "method": "POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "description": "The blood bank's name",
                                    "type": "string"
                                },
                                "address": {
                                    "title": "Address",
                                    "description": "The blood bank's address",
                                    "type": "string",
                                    "default":"-"
                                },
                                "city": {
                                    "title": "City",
                                    "description": "The blood bank's city",
                                    "type": "string"
                                },
                                "telephone": {
                                    "title": "Telephone",
                                    "description": "The blood bank's telephone",
                                    "type": "string"
                                },
                                "email": {
                                    "title": "Email",
                                    "description": "The blood bank's email",
                                    "type": "string"
                                },
                                "latitude": {
                                    "title": "Latitude",
                                    "description": "The blood bank's latitude",
                                    "type": "number"
                                },
                                "longitude": {
                                    "title": "Longitude",
                                    "description": "The blood bank's longitude",
                                    "type": "number"
                                },
                                "threshold": {
                                    "title": "Threshold",
                                    "description": "The blood bank's threshold of blood level to alert",
                                    "type": "number"
                                }
                            },
                            "required": ["name","city","telephone","email", "threshold"]
                        }
                    },
                    "bloodalert:donors-all": {
                        "title": "List all blood donors", 
                        "href": "/bloodalert/donors/"
                    },
                    
                    "bloodalert:blood-types-all": {
                        "title": "List all blood types", 
                        "href": "/bloodalert/bloodtypes/"
                    }
                }
            }


### Create a Blood Bank [POST]

Adds a new Blood Bank to the bloodAlert database
+ Request (application/json)
    
    The following are optional and defaults to `None`
    + `latitude`
    + `latitude`

    + Headers
    
            Accept: application/vnd.mason+json
    + Body
    
            {
                "name": "Oulun Tervestalo Veri Palvelu",
                "address": "Kajaanintie 50",
                "city": "Oulu",
                "telephone": "+358 8 3152011", 
                "email": "OuluUniHospital@oulu.fi",
                "latitude": 65.007406, "longitude": 25.517786,
                "threshold": 30
            }

+ Response 201 (application/json)
Blood Bank Created sucessfully
    + Headers

            Location: Url to the created Blood bank


+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include required body in correct format"
                    ]
                },
                "resource-url": "/bloodAlert/BloodBanks/"
            }


+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodAlert/BloodBanks/"
            }

+ Response 500  (application/vnd.mason+json)

    The server cannot store the Blood bank in the database.
    
    + Body 

            {
                "@error": {
                    "@message": "Blood bank could not be created",
                    "@messages": [
                        "Cannot create the blood bank in the database"
                    ]
                },
                "resource-url": "/bloodAlert/BloodBanks/"
            }

## Blood Bank [/bloodalert/bloodbanks/{bloodBankId}]
A blood bank information in the database

+ Parameters
    + bloodBankId (string,`bbank-1`) ... Id of the blood bank in the format bbank-\d{1,3}
                

### Get Blood Bank [GET]

Gets a blood bank information in the database


            
+ Response  200 (application/vnd.mason+json)

    Blood bank information loaded sucessfully
    
    + Body 
    
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalert/link-relations/"
                    }
                 },
                
                "bloodBankId": "bbank-1",
                "name": "Oulu University Hospital", 
                "address": "Kajaanintie 50",
                "city":"Oulu",
                "telephone":"+358 8 3152011",
                "email": "OuluUniHospital@oulu.fi",
                "latitude": 65.007406, 
                "longitude": 25.517786,
                "threshold": 30,
                
                "@controls": {
                    "self": {
                        "href": "/bloodalert/bloodbanks/bbank-1/"
                    },
                    "profile": {
                        "href": "/profiles/blood-banks-profile/"
                    },
                    "collection": {
                        "href": "/bloodalert/bloodbanks/"
                    },
                    "bloodalert:edit": {
                        "title": "Edit this blood bank",
                        "href": "/bloodalert/bloodbanks/bbank-1/",
                        "encoding": "json",
                        "method": "PUT",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "description": "The blood bank's name",
                                    "type": "string"
                                },
                                "address": {
                                    "title": "Address",
                                    "description": "The blood bank's address",
                                    "type": "string",
                                    "default":"-"
                                },
                                "city": {
                                    "title": "City",
                                    "description": "The blood bank's city",
                                    "type": "string"
                                },
                                "telephone": {
                                    "title": "Telephone",
                                    "description": "The blood bank's telephone",
                                    "type": "string"
                                },
                                "email": {
                                    "title": "Email",
                                    "description": "The blood bank's email",
                                    "type": "string"
                                },
                                "latitude": {
                                    "title": "Latitude",
                                    "description": "The blood bank's latitude",
                                    "type": "number"
                                },
                                "longitude": {
                                    "title": "Longitude",
                                    "description": "The blood bank's longitude",
                                    "type": "number"
                                },
                                "threshold": {
                                    "title": "Threshold",
                                    "description": "The blood bank's threshold of blood level to alert",
                                    "type": "number"
                                }
                            },
                            "required": []
                        }
                    },
                    "bloodalert:delete": {
                        "title":"Delete this blood bank",
                        "href": "/bloodalert/bloodbanks/bbank-1/",
                        "method": "DELETE"
                    },
                    "bloodalert:blood-bank-history-list": {
                        "title":"List History of this blood bank",
                        "href": "/bloodalert/bloodbanks/bbank-1/history/",
                        "method":"GET"
                    },
                    "bloodalert:blood-bank-blood-level": {
                        "title":"List blood levels of this blood bank",
                        "href": "/bloodalert/bloodbanks/bbank-1/bloodlevels/",
                        "method":"GET"
                    }
                }
            }
    
 
        
            
+ Response 404 (application/vnd.mason+json)
No such blood bank with specified Id

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood Bank",
                    "@messages": [
                        "No such blood bank with specified bbank-1"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1"
            }
   
### Modify Blood Bank [PUT]

Modifies a blood bank 

+ Request(application/json)

  
    Any or a combination of any of the optional parameters can be used
    
    + Headers
    
            Accept: application/vnd.mason+json
            
    + Body
    
            {
                
                "name": "Oulun Tervestalo Veri Palvelu",
                "address": "Kajaanintie 50",
                "city": "Oulu",
                "telephone": "+358 8 3152011", 
                "email": "OuluUniHospital@oulu.fi",
                "latitude": 65.007406, "longitude": 25.517786,
                "threshold": 30,
                "latitude":1.4539303039,
                "longitude":5.038377333
            
            }
            
+ Response 204 (application/vnd.mason+json)
    
  

+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include required headersall required parameters in the correct format "
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1"
            }
            
+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodalert/donors/"
            }

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank",
                    "@messages": [
                        " No such blood bank with id `bbank-1` exists in the database"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1"
            }  
            
+ Response 500 (application/vnd.mason+json)

    Blood bank with id `bbank-1` could not be modified
        
    + Body 
    
            {
                "@error": {
                    "@message": "Blood bank could not be modified",
                    "@messages": [
                        " Blood bank with id bbank-1 could not be modified"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1"
            }  
            
                        
### Delete Blood Bank [DELETE]
Delete a message from the system

+ Request(application/json)
    
    + Headers
    
            Accept: application/vnd.mason+json
    
+ Response 204

        
        

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank",
                    "@messages": [
                        " No such blood bank with id `bbank-1` exists in the database"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1"
            } 

## Blood Bank Blood levels [/bloodalert/bloodbanks/{bloodBankId}/bloodlevels/]
All blood levels (blood type and level of blood) of a particular blood bank

+ Parameters
    + bloodBankId (string,`bbank-1`) ... Id of the blood bank in the format bbank-\d{1,3}

### Get Blood Bank blood levels [GET]


                
+ Response 200 (application/vnd.mason+json)

     Blood bank blood levels loaded sucessfully 
     + Body 
    
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalart/link-relations/"
                    }
                },
                
                "items": [
                    {
                        "bloodype": "O+",
                        "amount": 50
                    },
                    {
                        "bloodype": "A+",
                        "amount": 150
                    },
                    {
                        "bloodype": "B+",
                        "amount": 33
                    }
                ],
                
                "@controls": {
                    "self": {
                        "href": "/bloodalert/bloodbanks/bbank-1/bloodlevels/"
                    },
                    "parent": {
                        "title": "The related blood bank",
                        "href": "/bloodalert/bloodbanks/bbank-1/",
                        "method": "GET"
                    }
                }
            }

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank",
                    "@messages": [
                        " No such blood bank with id `bbank-1` exists in the database"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1"
            }
            
## Blood Bank History List [/bloodalert/bloodbanks/{bloodBankId}/history/]
All blood bank blood transaction (donation , others) history
+ Parameters
    + bloodBankId (string,`bbank-1`) ... Id of the blood bank in the format bbank-\d{1,3}
    

### Get Blood Bank History List [GET]
Get all blood transactions of target blood bank (donation, etc)

            
+ Response  200 (application/vnd.mason+json)

    Blood bank history List loaded sucessfully
    
    + Body 
    
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalart/link-relations/"
                    }
                },
                
                "items": [
                    {
                        "historyId":"history-2",
                        "donorId":"bdonor-2",
                        "bloodTypeId":"btype-2",
                        "bloodBankId":"bbank-2",
                        "amount":300,
                        "timeStamp":"2016-10-08 13:54:12",
                        "tag":"DONATION",
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/bloodbanks/bbank-2/history/history-2/"
                            },
                            "profile": {
                                "href": "/profiles/blood-banks-profile/"
                            },
                            "donor":{
                                "href": "/bloodalert/donors/bdonor-2/"
                            },
                            "bloodbank":{
                                "href": "/bloodalert/bloodbanks/bbank-2/"
                            },
                            "bloodtype":{
                                "href": "/bloodalert/bloodtypes/btype-2/"
                            }
                        }
                    },
                    {
                        "historyId":"history-2",
                        "donorId":"bdonor-2",
                        "bloodTypeId":"btype-2",
                        "bloodBankId":"bbank-2",
                        "amount":300,
                        "timeStamp":"2016-10-08 13:54:12",
                        "tag":"DONATION",
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/bloodbanks/bbank-2/history/history-2/"
                            },
                            "profile": {
                                "href": "/profiles/blood-banks-profile/"
                            },
                            "donor":{
                                "href": "/bloodalert/donors/bdonor-2/"
                            },
                            "bloodbank":{
                                "href": "/bloodalert/bloodbanks/bbank-2/"
                            },
                            "bloodtype":{
                                "href": "/bloodalert/bloodtypes/btype-2/"
                            }                         
                        }
                    }
                ],
                
                "@controls": {
                    "self": {
                        "href": "/bloodalert/bloodbanks/bbank-2/history/"
                    },
                    "bloodalert:blood-bank-blood-level": {
                        "title":"List blood levels of this blood bank",
                        "href": "/bloodalert/bloodbanks/bbank-1/bloodlevels/",
                        "method":"GET"
                    }
                }
            }
 
        
            
+ Response 404 (application/vnd.mason+json)
No such blood bank with specified Id

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood Bank",
                    "@messages": [
                        "No such blood bank with specified bbank-1"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1/history"
            }
## Blood Bank History [/bloodalert/bloodbanks/{bloodBankId}/history/{historyId}/]
All blood bank blood transaction (donation , others) history
+ Parameters
    + bloodBankId (string,`bbank-1`) ... Id of the blood bank in the format bbank-\d{1,3}
    + historyId (string,`history-1`) ... Id of the blood Bank history entry in the format history -\d{1,3}

### Get Blood Bank History [GET]
Get a single blood bank history entry of target historyId


            
+ Response  200 (application/vnd.mason+json)

    Blood bank history information loaded sucessfully
    
    + Body
    
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalert/link-relations/"
                    }
                 },
                "historyId":"history-2",
                "donorId":"bdonor-2",
                "bloodTypeId":"btype-2",
                "bloodBankId":"bbank-2",
                "amount":300,
                "timeStamp":"2016-10-08 13:54:12",
                "tag":"DONATION",
                "@controls": {
                    "self": {
                        "href": "/bloodalert/bloodbanks/bbank-2/history/history-2/"
                            },
                    "profile": {
                        "href": "/profiles/blood-banks-profile/"
                    },
                    "donor":{
                        "href": "/bloodalert/donors/bdonor-2/"
                    },
                    "bloodbank":{
                        "href": "/bloodalert/bloodbanks/bbank-2/"
                    },
                    "bloodtype":{
                        "href": "/bloodalert/bloodtypes/btype-2/"
                    },      
                    "bloodalert:edit": {
                        "title": "Edit this blood bank history",
                        "href": "/bloodalert/bloodbanks/bbank-2/history/history-2/",
                        "encoding": "json",
                        "method": "PUT",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "donorId": {
                                    "title": "Blood Donor",
                                    "description": "The Blood Donor's Id",
                                    "type": "string"
                                },
                                "bloodTypeId": {
                                    "title": "Blood Type",
                                    "description": "The blood type Id",
                                    "type": "string"
                                },
                                "amount": {
                                    "title": "Amount",
                                    "description": "The amount of blood",
                                    "type": "string"
                                },
                                "timeStamp": {
                                    "title": "Time",
                                    "description": "The timeStamp of blood bank history",
                                    "type": "string"
                                },
                                "tag": {
                                    "title": "Tag",
                                    "description": "The tag of the donation history",
                                    "type": "string",
                                    "default":"DONATION"
                                }
                            },
                            "required": []
                        }
                    },
                    "bloodalert:delete": {
                        "title":"Delete this blood bank history",
                        "href": "/bloodalert/bloodbanks/bbank-2/history/history-2/",
                        "method": "DELETE"
                    },
                    "bloodalert:blood-bank-history-list": {
                        "title":"List History of this blood bank",
                        "href": "/bloodalert/bloodbanks/bbank-2/history/",
                        "method":"GET"
                    },
                    "bloodalert:blood-bank-blood-level": {
                        "title":"List blood levels of this blood bank",
                        "href": "/bloodalert/bloodbanks/bbank-1/bloodlevels/",
                        "method":"GET"
                    }
                }
            }
 
        
            
+ Response 404 (application/vnd.mason+json)
No such blood bank  with specified Blood bloodBankId or historyId

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood Bank",
                    "@messages": [
                        "No such blood bank with specified bbank-1"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            }

### Modify Blood Bank History [PUT]
Modifies blood bank history 

+ Request(application/json)
    
    Any of ( or a combination of ) the following of a Blood Bank History ;
    
    + ``donorId``
    + ``bloodTypeId``
    + ``amount``
    + ``timeStamp``
    +   Headers
    
            Accept: application/vnd.mason+json
            
+ Response 204 (application/vnd.mason+json)
    
  

+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include required headersall required parameters in the correct format "
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            }
            
+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodalert/donors/"
            }

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` and historyId `history-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank history",
                    "@messages": [
                        "No such blood bank with id bbank-1 and historyId history-1 exists in the database"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            }         

+ Response 500 (application/vnd.mason+json)

    Blood bank history with id `bbank-1` and historyId `history-1` could bot be modified
        
    + Body 
    
            {
                "@error": {
                    "@message": "Blood bank history could not be modified",
                    "@messages": [
                        "Blood bank history with id `bbank-1` and historyId `history-1` could bot be modified"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            }     

### Delete Blood Bank History [DELETE]
Delete a blood bank donation history from the database

+ Request(application/json)
    
    + Headers
    
            Accept: application/vnd.mason+json
    
+ Response 204

        
        

+ Response 404 (application/vnd.mason+json)

    No such blood bank with id `bbank-1` and historyId `history-1` exists in the databaseNo such blood bank with id `bbank-1` exists in the database
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood bank history",
                    "@messages": [
                        "No such blood bank with id `bbank-1` and historyId `history-1` exists in the database"
                    ]
                },
                "resource-url": "/bloodalert/bloodbanks/bbank-1/history/history-1"
            } 


# Group Blood Donors

All these resources use the [Blood Donor Profile](reference/profiles/blood-donor-profile).

In addition all error messages follow the profile defined [Error Profile](reference/profiles/error-profile).

## Blood Donor List [/bloodalert/donors/]
All Blood Donors in the database

### List all Blood Donors  [GET]
Gets a list of all blood donors 
            
+ Response  200 (application/vnd.mason+json)

    Blood donor List loaded sucessfully
    
    + Body
     
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalart/link-relations/"
                    }
                },
                "items": [
                    {
                        "donorId": "bdonor-1",
                        "firstname": "Anna", 
                        "familyName": "Bord",
                        "birthDate": "30-12-1986", 
                        "gender": "Female",
                        "bloodTypeId": "btype-1", 
                        "telephone": "+348416754234",
                        "city": "Oulu", 
                        "address": "Linnanmaa", 
                        "email": "AnB@oulu.fi",
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/donors/bdonor-1/"
                            },
                            "profile": {
                                "href": "/profiles/blood-donors-profile/"
                            },
                            "bloodtype":{
                                "href": "/bloodalert/bloodtypes/btype-1/"
                            }                            
                        }
                    },
                    {
                        "donorId": "bdonor-2",
                        "firstname": "Marcela", 
                        "familyName": "Storm",
                        "birthDate": "20-12-1996", 
                        "gender": "Female",
                        "bloodTypeId": "btype-2", 
                        "telephone": "+348417856964",
                        "city": "Oulu", 
                        "address": "Linnanmaa", 
                        "email": "ms@oulu.fi",
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/donors/bdonor-2/"
                            },
                            "profile": {
                                "href": "/profiles/blood-donors-profile/"
                            },
                            "bloodtype":{
                                "href": "/bloodalert/bloodtypes/btype-2/"
                            }                            
                        }
                    }
                ],
                "@controls": {
                    "self": {
                        "href": "/bloodalert/donors/"
                    },
                    "bloodalert:add-blood-donor": {
                        "title": "Add Blood Donor",
                        "href": "/bloodalert/donors/",
                        "encoding": "json",
                        "method": "POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "firstname": {
                                    "title": "FirstName",
                                    "description": "The blood donor's firstname",
                                    "type": "string"
                                },
                                "familyname": {
                                    "title": "Family Name",
                                    "description": "The blood donor's familyname",
                                    "type": "string"
                                },
                                "birthDate": {
                                    "title": "Birth Date",
                                    "description": "The blood donor's birth Date",
                                    "type": "string"
                                },
                                "gender": {
                                    "title": "Gender",
                                    "description": "The blood donor's gender",
                                    "type": "string"
                                },
                                "bloodTypeId": {
                                    "title": "Blood Type",
                                    "description": "The blood donor's bloodType Id",
                                    "type": "string"
                                },
                                "telephone": {
                                    "title": "Telephone",
                                    "description": "The blood donor's telephone",
                                    "type": "string"
                                },
                                "city": {
                                    "title": "City",
                                    "description": "The blood donor's city",
                                    "type": "string"
                                },
                                "address": {
                                    "title": "Address",
                                    "description": "The blood donor's address",
                                    "type": "string"
                                },
                                "email": {
                                    "title": "Email",
                                    "description": "The blood donor's email",
                                    "type": "string"
                                }
                            },
                            "required": ["firstname","familyName","birthDate","gender","bloodTypeId","telephone","address","email"]
                        }
                    },
                    "bloodalert:blood-banks-all": {
                        "title": "List all blood banks", 
                        "href": "/bloodalert/bloodbanks/"
                    },
                    
                    "bloodalert:blood-types-all": {
                        "title": "List all blood types", 
                        "href": "/bloodalert/bloodtypes/"
                    }
                }
            }



### Create a new Blood Donor [POST]

Adds a new Blood Donor to the bloodAlert database
+ Request (application/json)
    
    The following are optional  
    + `address` defaults to `-`
    + `city` defaults to `None`
   

    + Headers
    
            Accept: application/vnd.mason+json
    + Body
    
            {
                "firstname": "Anna",
                "familyName": "Bord",
                "telephone": "+348416754234", 
                "email": "AnB@oulu.fi",
                "bloodTypeId": "btype-1", 
                "birthDate": "30-12-1986",
                "gender": "Female",
                "address": "Yliopistokatu 46 , Linnanmaa",
                "city": "Oulu"
            }

+ Response 201 (application/json)
Blood donor Created sucessfully
    + Headers

            Location: Url to the created Blood donor


+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include required body in correct format"
                    ]
                },
                "resource-url": "/bloodalert/donors/"
            }


+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodalert/donors/"
            }

+ Response 500  (application/vnd.mason+json)

    The server cannot store the blood donor in the database.
    
    + Body 

            {
                "@error": {
                    "@message": "Blood donor could not be created",
                    "@messages": [
                        "Cannot create the blood donor in the database"
                    ]
                },
                "resource-url": "/bloodalert/donors/"
            }

## Blood Donor [/bloodalert/donors/{donorid}/]
A blood donor in the database

+ Parameters
    + donorid (string,`bdonor-1`) ... Id of the blood donor in the format bdonor-\d{1,3}
   
    
### Get Blood Donor [GET]

Gets a blood donor information in the database



            
+ Response  200 (application/vnd.mason+json)

    Blood donor information loaded sucessfully
    
    + Body 
    
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalert/link-relations/"
                    }
                 },
                "donorId": "bdonor-2",
                "firstname": "Marcela", 
                "familyName": "Storm",
                "birthDate": "20-12-1996", 
                "gender": "Female",
                "bloodTypeId": "btype-2", 
                "telephone": "+348417856964",
                "city": "Oulu", 
                "address": "Linnanmaa", 
                "email": "ms@oulu.fi",
                "@controls": {
                    "self": {
                            "href": "/bloodalert/donors/bdonor-2/"
                        },
                    "profile": {
                        "href": "/profiles/blood-donors-profile/"
                    },
                    "bloodtype":{
                        "href": "/bloodalert/bloodtypes/btype-2/"
                    },  
                    "collection": {
                        "href": "/bloodalert/donors/"
                    },
                    "bloodalert:edit": {
                        "title": "Edit this blood donor",
                        "href": "/bloodalert/donors/bdonor-2/",
                        "encoding": "json",
                        "method": "PUT",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "firstname": {
                                    "title": "FirstName",
                                    "description": "The blood donor's firstname",
                                    "type": "string"
                                },
                                "familyname": {
                                    "title": "Family Name",
                                    "description": "The blood donor's familyname",
                                    "type": "string"
                                },
                                "birthDate": {
                                    "title": "Birth Date",
                                    "description": "The blood donor's birth Date",
                                    "type": "string"
                                },
                                "gender": {
                                    "title": "Gender",
                                    "description": "The blood donor's gender",
                                    "type": "string"
                                },
                                "bloodTypeId": {
                                    "title": "Blood Type",
                                    "description": "The blood donor's bloodType Id",
                                    "type": "string"
                                },
                                "telephone": {
                                    "title": "Telephone",
                                    "description": "The blood donor's telephone",
                                    "type": "string"
                                },
                                "city": {
                                    "title": "City",
                                    "description": "The blood donor's city",
                                    "type": "string"
                                },
                                "address": {
                                    "title": "Address",
                                    "description": "The blood donor's address",
                                    "type": "string"
                                },
                                "email": {
                                    "title": "Email",
                                    "description": "The blood donor's email",
                                    "type": "string"
                                }
                            },
                            "required": []
                        }
                    },
                    "bloodalert:delete": {
                        "title":"Delete this blood donor",
                        "href": "/bloodalert/donors/bdonor-2/",
                        "method": "DELETE"
                    },
                    "bloodalert:blood-donor-history-list": {
                        "title":"List donation History of this blood donor",
                        "href": "/bloodalert/donors/bdonor-2/history/",
                        "method":"GET"
                    }
                }
            }
    
 
        
            
+ Response 404 (application/vnd.mason+json)
No such blood donor with specified Id

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood donor",
                    "@messages": [
                        "No such blood donor with specified bdonor-2"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2"
            }

### Modify Blood donor [PUT]
Modifies a blood donor 

+ Request(application/json)
    
    Any of ( or a combination of ) the following of a Blood donor; 
    
    + ``firstname`` 
    + ``familyName``
    + ``telephone``
    + ``email``
    + ``bloodTypeId``
    + ``birthDate``
    + ``gender``
    + ``address``
    + ``city``
    
    
    +   Headers
    
            Accept: application/vnd.mason+json
            
    +   Body
            
            {
                "firstname":"Anas",
                "telephone":"+358546933723"
            }
    
            
+ Response 204 (application/vnd.mason+json)
    
  

+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include required headersall required parameters in the correct format "
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2"
            }
            
+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2"
            }

+ Response 404 (application/vnd.mason+json)

    No such blood donor with id `bdonor-2`
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood donor",
                    "@messages": [
                        "No such blood donor with id bdnor-2"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2"
            } 
            
+ Response 500 (application/vnd.mason+json)

    Blood donor with id `bdonor-2` could not be modified
        
    + Body 
    
            {
                "@error": {
                    "@message": "Blood donor could not be modified",
                    "@messages": [
                        "Blood donor with id bdonor-2 could not be modified"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2"
            }
            
### Delete Blood donor [DELETE]
Delete a blood donor

+ Request(application/json)
    
    + Headers
    
            Accept: application/vnd.mason+json
    
+ Response 204

        
+ Response 404 (application/vnd.mason+json)

    No such blood donor with id `bdonor-2`
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood donor",
                    "@messages": [
                        "No such blood donor with id bdnor-2"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2"
            } 


## Blood Donor History List [/bloodalert/donors/{donorid}/history/]

All Blood Donar donation history in the database

+ Parameters
    + donorid (string,`bdonor-1`) ... Id of the blood donor in the format bdonor-\d{1,3}

### List All Blood donor donations [GET]

Get a list of all Blood donor donation in the system

+ Response 200 (application/vnd.mason+json)

    Blood donor donation  List loaded sucessfully
    
    + Body 
        
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalart/link-relations/"
                    }
                },
                "items": [
                    {
                        "historyId":"history-2",
                        "donorId":"bdonor-2",
                        "bloodTypeId":"btype-2",
                        "bloodBankId":"bbank-2",
                        "amount":300,
                        "timeStamp":"2016-10-08 13:54:12",
                        "tag":"DONATION",
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/donors/bdonor-2/history/history-2/"
                            },
                            "profile": {
                                "href": "/profiles/blood-donors-profile/"
                            },
                            "donor":{
                                "href": "/bloodalert/donors/bdonor-2/"
                            },
                            "bloodbank":{
                                "href": "/bloodalert/bloodbanks/bbank-2/"
                            },
                            "bloodtype":{
                                "href": "/bloodalert/bloodtypes/btype-2/"
                            }
                        }
                    },
                    {
                        "historyId":"history-3",
                        "donorId":"bdonor-2",
                        "bloodTypeId":"btype-2",
                        "bloodBankId":"bbank-2",
                        "amount":300,
                        "timeStamp":"2016-10-08 13:54:12",
                        "tag":"DONATION",
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/donors/bdonor-2/history/history-3/"
                            },
                            "profile": {
                                "href": "/profiles/blood-donors-profile/"
                            },
                            "donor":{
                                "href": "/bloodalert/donors/bdonor-2/"
                            },
                            "bloodbank":{
                                "href": "/bloodalert/bloodbanks/bbank-2/"
                            },
                            "bloodtype":{
                                "href": "/bloodalert/bloodtypes/btype-2/"
                            }               
                        }
                    }
                ],
                "@controls": {
                    "self": {
                        "href": "/bloodalert/donors/bdonor-2/history/"
                    },
                    "bloodalert:blood-donor-donate": {
                        "title":"Create Blood Donation ",
                        "href": "/bloodalert/donors/bdonor-2/history/",
                        "method":"POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "bloodTypeId": {
                                    "title": "Blood Type",
                                    "description": "The blood donor's bloodTypeId",
                                    "type": "string"
                                },
                                "bloodBankId": {
                                    "title": "Blood bank",
                                    "description": "The blood bank of the blood donation",
                                    "type": "string"
                                },
                                "amount": {
                                    "title": "Amount of Blood donated",
                                    "description": "The amount of blood donated",
                                    "type": "string"
                                },
                                "timeStamp": {
                                    "title": "Time of Donation",
                                    "description": "The timeStamp of blood donated",
                                    "type": "string"
                                }
                                
                            },
                            "required": ["bloodTypeId","bloodBankId","amount"]
                        }
                    }
                }
                
            }


### Create Blood donor donation [POST]

Adds a new Blood donor donation to the bloodAlert database
+ Request (application/json)
    

    + Headers
    
            Accept: application/vnd.mason+json
    + Body
    
            {
                "bloodTypeId": "btype-1",
                "bloodBankId": "bbank-1",
                "amount": "240",
                "timeStamp": "2016-10-08 13:54:12"
            }

+ Response 201 (application/json)
Blood Donor donation Created sucessfully
    + Headers

            Location: Url to the created Blood Donor donation


+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include required body in correct format"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/"
            }


+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/"
            }

+ Response 500  (application/vnd.mason+json)

    The server cannot store the Blood donor donation in the database.
    
    + Body 

            {
                "@error": {
                    "@message": "Blood donor donation could not be created",
                    "@messages": [
                        "Cannot create the blood donor donation in the database"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/"
            }

## Blood Donation History [/bloodalert/donors/{donorId}/history/{historyId}/]
All blood donor donation history
+ Parameters
    + donorId (string,`bdonor-2`) ... Id of the blood donor in the format bdonor-\d{1,3}
    + historyId (string,`history-2`) ... Id of the blood donation history entry in the format history -\d{1,3}

### Get Blood Donation History [GET]
Get a single blood donor donation history entry of target historyId


            
+ Response  200 (application/vnd.mason+json)

    Blood bank history information loaded sucessfully
    
    + Body
    
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalert/link-relations/"
                    }
                 },
                "historyId":"history-2",
                "donorId":"bdonor-2",
                "bloodTypeId":"btype-2",
                "bloodBankId":"bbank-2",
                "amount":300,
                "timeStamp":"2016-10-08 13:54:12",
                "tag":"DONATION",
                "@controls": {
                    "self": {
                        "href": "/bloodalert/donors/bdonor-2/history/history-2/"
                    },
                    "profile": {
                        "href": "/profiles/blood-donors-profile/"
                    },
                    "donor":{
                        "href": "/bloodalert/donors/bdonor-2/"
                    },
                    "bloodbank":{
                        "href": "/bloodalert/bloodbanks/bbank-2/"
                    },
                    "bloodtype":{
                        "href": "/bloodalert/bloodtypes/btype-2/"
                    },
                    "bloodalert:edit":{
                        "title":"Modify Blood Donation ",
                        "href": "/bloodalert/donors/bdonor-2/history/history-2/",
                        "method":"PUT",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "bloodTypeId": {
                                    "title": "Blood Type",
                                    "description": "The blood donor's bloodTypeId",
                                    "type": "string"
                                },
                                "bloodBankId": {
                                    "title": "Blood bank",
                                    "description": "The blood bank of the blood donation",
                                    "type": "string"
                                },
                                "amount": {
                                    "title": "Amount of Blood donated",
                                    "description": "The amount of blood donated",
                                    "type": "string"
                                },
                                "timeStamp": {
                                    "title": "Time of Donation",
                                    "description": "The timeStamp of blood donated",
                                    "type": "string"
                                }
                            },
                            "required": []
                        }
                    },
                    "bloodalert:delete":{
                        "title":"Modify Blood Donation ",
                        "href": "/bloodalert/donors/bdonor-2/history/history-2/",
                        "method":"DELETE"
                    },
                    "bloodalert:blood-donor-history-list":{
                        "title":"List donation History of this blood donor",
                        "href": "/bloodalert/donors/bdonor-2/history/",
                        "method":"GET"
                    }
                }
            }
 
        
            
+ Response 404 (application/vnd.mason+json)
    No such blood donation  with specified  donorId or historyId

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood donation",
                    "@messages": [
                        "No such blood donation  with specified  donorId or historyId"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/history-2/"
            }

### Modify Blood Donation History [PUT]
Modifies blood donor donation history 

+ Request(application/json)
    
    Any of ( or a combination of ) the following of a Blood donation history; 
    
    + ``bloodBankId`` 
    + ``amount``
    + ``timeStamp``
    
    
    +   Headers
    
            Accept: application/vnd.mason+json
            
    +   Body
            
            {
                "bloodBankId":"bbank-2",
                "amount":300,
                "timeStamp":"2016-10-08 13:54:12"
            }
    
            
+ Response 204 (application/vnd.mason+json)
    
  

+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include required headersall required parameters in the correct format "
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/history-2/"
            }
            
+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/history-2/"
            }

+ Response 404 (application/vnd.mason+json)

    No such blood donation  with specified  donorId or historyId

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood donation",
                    "@messages": [
                        "No such blood donation  with specified  donorId or historyId"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/history-2/"
            }
            
+ Response 500 (application/vnd.mason+json)

    Blood donation history with id `history-2` could not be modified
        
    + Body 
    
            {
                "@error": {
                    "@message": "Blood donation history could not be modified",
                    "@messages": [
                        "Blood donation history with id history-` could not be modified"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/history-2/"
            } 



### Delete Blood Donation History [DELETE]
Delete a blood donation history

+ Request(application/json)
    
    + Headers
    
            Accept: application/vnd.mason+json
    
+ Response 204

        
+ Response 404 (application/vnd.mason+json)

    No such blood donation  with specified  donorId or historyId

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood donation",
                    "@messages": [
                        "No such blood donation  with specified  donorId or historyId"
                    ]
                },
                "resource-url": "/bloodalert/donors/bdonor-2/history/history-2/"
            }


    
# Group Blood Types

All these resources use the [Blood Type Profile](reference/profiles/blood-types-profile).

In addition all error messages follow the profile defined [Error Profile](reference/profiles/error-profile).

## Blood Types List [/bloodalert/bloodtypes/]

All Blood Types in the database

### List all Blood Types  [GET]
Gets a list of all blood types 
            
+ Response  200 (application/vnd.mason+json)

    Blood type List loaded sucessfully
    
    + Body
     
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalart/link-relations/"
                    }
                },
                "items": [
                    {
                        "bloodTypeId": "btype-1",
                        "name": "0+", 
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/bloodtypes/btype-1/"
                            },
                            "profile": {
                                "href": "/profiles/blood-types-profile/"
                            }                           
                        }
                    },
                    {
                        "bloodTypeId": "btype-2",
                        "name": "A+", 
                        "@controls": {
                            "self": {
                                "href": "/bloodalert/bloodtypes/btype-1/"
                            },
                            "profile": {
                                "href": "/profiles/blood-types-profile/"
                            }                           
                        }
                    }
                ],
                "@controls": {
                    "self": {
                        "href": "/bloodalert/bloodtypes/"
                    },
                    "bloodalert:add-blood-type": {
                        "title": "Add Blood Type",
                        "href": "/bloodalert/bloodtypes/",
                        "encoding": "json",
                        "method": "POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Blood Type",
                                    "description": "The blood type's name",
                                    "type": "string"
                                }
                            },
                            "required": ["name"]
                        }
                    },
                    "bloodalert:blood-banks-all": {
                        "title": "List all blood banks", 
                        "href": "/bloodalert/bloodbanks/"
                    },
                    
                    "bloodalert:donors-all": {
                        "title": "List all blood donors", 
                        "href": "/bloodalert/donors/"
                    }
                }
            }
### Create a Blood Type [POST]

Adds a new Blood type to the bloodAlert database
+ Request (application/json)

    + Headers
    
            Accept: application/vnd.mason+json
    + Body
    
            {
                "name": "AB+"
            }

+ Response 201 (application/json)
Blood type Created sucessfully
    + Headers

            Location: Url to the created Blood type


+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include all required request body"
                    ]
                },
                "resource-url": "/bloodAlert/bloodtypes/"
            }


+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodAlert/bloodtypes/"
            }

+ Response 500  (application/vnd.mason+json)

    The server cannot store the blood type in the database.
    
    + Body 

            {
                "@error": {
                    "@message": "Blood type could not be created",
                    "@messages": [
                        "Cannot create a blood type in the database"
                    ]
                },
                "resource-url": "/bloodAlert/bloodtypes/"
            }
            
## Blood Type [/bloodalert/bloodtypes/{bloodTypeId}/]
A blood type in the database

+ Parameters
    + bloodTypeId (string,`btype-1`) ... Id of the blood type in the format btype-\d{1,3}

    
### Get Blood type [GET] 

Gets a blood type information in the database



+ Response  200 (application/vnd.mason+json)

    Blood type loaded sucessfully
    
    + Body 
    
            {
                "@namespaces": {
                    "bloodalert": {
                        "name": "/bloodalert/link-relations/"
                    }
                 },
                "bloodTypeId": "btype-1",
                "name": "O+", 
                "@controls": {
                    "self": {
                        "href": "/bloodalert/bloodtypes/btype-1/"
                    },
                    "profile": {
                        "href": "/profiles/blood-types-profile/"
                    },
                    "collection": {
                        "href": "/bloodalert/bloodtypes/"
                    },
                    "bloodalert:edit": {
                        "title": "Edit this blood type",
                        "href": "/bloodalert/bloodtypes/btype-1/",
                        "encoding": "json",
                        "method": "PUT",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "description": "The blood type's name",
                                    "type": "string"
                                }
                            },
                            "required": ["name"]
                        }
                    },
                    "bloodalert:delete": {
                        "title":"Delete this blood blood type",
                        "href": "/bloodalert/bloodtype/btype-1/",
                        "method": "DELETE"
                    }
                }
            }
    
 
+ Response 404 (application/vnd.mason+json)
No such blood bank with specified Id

    
    + Body
    
            {
                "@error": {
                    "@message": "No such Blood Type",
                    "@messages": [
                        "No such blood bank with specified btype-1"
                    ]
                },
                "resource-url": "/bloodalert/bloodtypes/btype-1"
            }

### Modify Blood type [PUT]

Modifies blood type

+ Request(application/json)
    
    + `name` (string) - the name of the blood type
    
    +   Headers
    
            Accept: application/vnd.mason+json
            
    +   Body
            
            {
                "name":"O+"
            }
            
+ Response 204 (application/vnd.mason+json)
    
  

+ Response 400 (application/vnd.mason+json)
The request body is malformed. Some of the the parameters are not correctly provided

    
    + Body
    
            {
                "@error": {
                    "@message": "Wrong request format",
                    "@messages": [
                        "Be sure to include required headersall required parameters in the correct format "
                    ]
                },
                "resource-url": "/bloodalert/bloodtypes/btype-1"
            }
            
+ Response 415 (application/vnd.mason+json)

    The server cannot understand the format of the response.
    
    + Body 
    
            {
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use a JSON compatible format"
                    ]
                },
                "resource-url": "/bloodalert/bloodtypes/btype-1"
            }

+ Response 404 (application/vnd.mason+json)

    No such blood type with id `btype-1`
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood type",
                    "@messages": [
                        "No such blood type with id btype-1"
                    ]
                },
                "resource-url": "/bloodalert/bloodtypes/btype-1"
            } 
            
+ Response 500 (application/vnd.mason+json)

    Blood type with id `btype-1` could not be modified
        
    + Body 
    
            {
                "@error": {
                    "@message": "Blood type could not be modified",
                    "@messages": [
                        "Blood type with id btype-1 could not be modified"
                    ]
                },
                "resource-url": "/bloodalert/bloodtypes/btype-1"
            } 

### Delete Blood type [DELETE]
Delete a blood type

+ Request(application/json)
    
    + Headers
    
            Accept: application/vnd.mason+json
    
+ Response 204
    
        
        

+ Response 404 (application/vnd.mason+json)

    No such blood type with id `btype-1`
        
    + Body 
    
            {
                "@error": {
                    "@message": "No such Blood typoe",
                    "@messages": [
                        "No such blood type with id btype-1"
                    ]
                },
                "resource-url": "/bloodalert/bloodtypes/btype-1"
            }

